---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: {{ .Values.imagePullSecrets }}
          containers:
          - name: topstories
            image: bh7cw/topstories:1.0
            imagePullPolicy: IfNotPresent
          - name: newstories
            image: bh7cw/newstories:1.0
            imagePullPolicy: IfNotPresent
          - name: beststories
            image: bh7cw/beststories:1.0
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure