apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  MYSQL_DB_USERNAME: {{ .Values.mysql.dbUsername | b64enc | quote }}
  MYSQL_DB_PASSWORD: {{ .Values.mysql.dbPassword | b64enc | quote }}