apiVersion: v1
kind: Secret
metadata:
  name: {{ template "webapp.name" . }}-db-secret
type: Opaque
data:
  MYSQL_DB_USERNAME: {{ .Values.mysql.dbUsername | b64enc }}
  MYSQL_DB_PASSWORD: {{ .Values.mysql.dbPassword | b64enc }}