version: v1

image:
  repository: bh7cw/webapp
  name: webapp

imagePullSecrets: docker-hub
port: 8080

readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 45
  periodSeconds: 5

livenessProbe:
  path: /v1/helloworld
  initialDelaySeconds: 60
  periodSeconds: 5

resources:
  memory: 256Mi
  cpu: 500m

hpa:
  minReplicas: 1
  maxReplicas: 2
  target:
    averageUtilization: 50

mysql:
  dbHost: 35.229.122.10
  dbPort: 3306
  dbName: csye7125
  spring: prod
  dbUsername: root
  dbPassword: MysqlPwd123

kafka:
  host: kafka.default.svc.cluster.local
  port: 9092

deployment:
  replicas: 1
  progressDeadlineSeconds: 600
  minReadySeconds: 30
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate
  # Monitoring: Adjust Prometheus configuration
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
  svc:
    port: 80

cronjob:
  schedule: "*/10 * * * *"
  imagePullPolicy: Always
  restartPolicy: OnFailure
  top:
    name: topstories
    image: bh7cw/topstories:latest
  new:
    name: newstories
    image: bh7cw/newstories:latest
  best:
    name: beststories
    image: bh7cw/beststories:latest