image:
  repository: bh7cw/webapp
  name: webapp

imagePullSecrets: docker-hub
port: 8080

readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 45
  periodSeconds: 5

livenessProbe:
  path: /v1/helloworld
  initialDelaySeconds: 60
  periodSeconds: 5

resources:
  memory: 256Mi
  cpu: 500m

hpa:
  minReplicas: 1
  maxReplicas: 2
  target:
    averageUtilization: 5

mysql:
  dbHost: rds.cvefazkbfyp3.us-east-1.rds.amazonaws.com
  dbPort: 3306
  dbName: csye7125
  spring: prod
  dbUsername: root
  dbPassword: MysqlPwd123

deployment:
  replicas: 3
  progressDeadlineSeconds: 600
  minReadySeconds: 30
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate
  # Monitoring: Adjust Prometheus configuration
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
  svc:
    port: 80

cronjob:
  schedule: "*/10 * * * *"
  imagePullPolicy: IfNotPresent
  restartPolicy: OnFailure
  top:
    name: topstories
    image: bh7cw/topstories:latest
  new:
    name: newstories
    image: bh7cw/newstories:latest
  best:
    name: beststories
    image: bh7cw/beststories:latest